---
kind: pipeline
name: building

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: clone
    pull: always
    image: alpine/git:latest
    commands:
    - git clone $DRONE_REMOTE_URL
    - cd $DRONE_REPO_NAME
    - git checkout $DRONE_BRANCH
    when:
      event:
        exclude:
        - pull_request
##################################################
  - name: build_docker_img
    pull: always
    image: docker:latest
    commands:
    - cd $DRONE_REPO_NAME
    - docker login -u mazgis47 -p $PLUGIN_DOCKERHUB_TOKEN
    - docker build --network host -t mazgis47/test-web-app:latest .
    - docker push mazgis47/test-web-app:latest
    settings:
      DOCKERHUB_TOKEN:
          from_secret: dockerhub_token
    when:
      event:
        exclude:
        - pull_request
    volumes:
    - name: docker
      path: /var/run/docker.sock
    depends_on:
    - clone
##################################################
  - name: generate_manifest
    image: bitnami/kubectl:latest
    commands:
    - cd $DRONE_REPO_NAME
    - pwd
    - ls -la
    - kubectl kustomize kubernetes/overlays/test
    - kubectl kustomize kubernetes/overlays/test > app.yaml
    settings:
      KUBE_CONFIG:
          from_secret: kube_config
    when:
      event:
        exclude:
        - pull_request
    depends_on:
    - build_docker_img
##################################################
  - name: push_manifest
    pull: always
    image: alpine/git:latest
    commands:
    - git clone https://github.com/Mazgis47/gitops.git
    - cp $DRONE_REPO_NAME/app.yaml gitops/
    - cd gitops
    - git config user.name "Releaser"
    - git config user.email "releaserd@noone.com"
    - git add -A
    - git commit -m "Releasing $DRONE_COMMIT_SHA"
    - AUTH_HEADER=$(echo -n "n:$GITHUB_TOKEN" |base64 );
    - |
      git -c http.extraheader="AUTHORIZATION: Basic ${AZURE_AUTH_HEADER}" push
    settings:
      GITHUB_TOKEN:
          from_secret: github_token
    when:
      event:
        exclude:
        - pull_request
    depends_on:
    - generate_manifest
##################################################

trigger:
  event:
    exclude:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
