apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/volume/drone"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
# ---
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: aws-secrets
# spec:
#   provider: aws
#   secretObjects:
#     - secretName: drone-secret
#       type: Opaque
#       data:
#         - objectName: GITHUB_CLIENT_SECRET
#           key: GITHUB_CLIENT_SECRET
#         - objectName: RPC_SECRET
#           key: RPC_SECRET
#   parameters:
#     objects: |
#         - objectName: "arn:aws:secretsmanager:us-east-2:173609628671:secret:drone-secret-kMUllj"
#           objectType: "secretsmanager"
#         # - objectName: "arn:aws:secretsmanager:us-east-2:173609628671:secret:GITHUB_CLIENT_SECRET-rLyEDD"
#         #   objectType: "secretsmanager"
#         # - objectName: "arn:aws:secretsmanager:us-east-2:173609628671:secret:RPC_SECRET-zMZXUW"
#         #   objectType: "secretsmanager"
#         # - objectName: "GITHUB_CLIENT_SECRET"
#         #   objectType: "secretsmanager"
#         # - objectName: "RPC_SECRET"
#         #   objectType: "secretsmanager"
