apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-website
      group: demo-website
  template:
    spec:
      containers:
        - name: demo-website
          image: mazgis47/demo-website:image_tag_placeholder
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: demo-website