apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-website
    name: demo-website-http
  name: demo-website-http
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: demo-website
    group: demo-website
